spring.application.name=JWT_Gateway
server.port=8080
jwt.secret=dfghjklsdfghjkldfghjkl;rtyuiopdfghjklxcvbnm,dfghjkdfghj
spring.main.web-application-type=reactive
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Cú pháp chu?n hóa l?i cho Properties m?ng c?a Spring Boot m?i:
#spring.cloud.gateway.routes[0].id=product-service-route
#spring.cloud.gateway.routes[0].uri=lb://PRODUCTSERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/products/**
# B?t log trace cho toàn b? h? th?ng ??nh tuy?n Gateway
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=TRACE
logging.level.org.springframework.web.reactive=TRACE
logging.level.reactor.netty=DEBUG