//plugins {
//    id 'java'
//    id 'org.springframework.boot' version '4.0.5'
//    id 'io.spring.dependency-management' version '1.1.7'
//}
// Hạ phiên bản xuống thấp để có thể sử dụng đc Redis Session
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4' // Hạ từ 4.0.5 xuống 3.3.4
    id 'io.spring.dependency-management' version '1.1.6' // Đồng bộ bản dependency
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'Session11_Redis_Cache'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.security:spring-security-test'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
    // 1. Thư viện hỗ trợ cơ chế Caching chung của Spring
    implementation 'org.springframework.boot:spring-boot-starter-cache'

    // 2. Thư viện kết nối và làm việc cụ thể với Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.redisson:redisson-spring-boot-starter:3.17.0'

    implementation 'org.springframework.session:spring-session-data-redis'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
}

tasks.named('test') {
    useJUnitPlatform()
}
